### ISSUE TITLE
Error in console with drop triggered

### ISSUE THREAD

**Issue by honnisha** [Seyarada/PandeLoot#1]
Error triggered when player kill mob with droptable

Error from console:
```
[23:21:15 WARN]: [PandeLoot] Task #29045 for PandeLoot v0.1.5 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LOOT0TO10
at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
at org.bukkit.Material.valueOf(Material.java:90) ~[patched_1.16.5.jar:git-Paper-623]
at net.seyarada.pandeloot.rewards.RewardLine.getItemStack(RewardLine.java:159) ~[?:?]
at net.seyarada.pandeloot.drops.DropItem.doDrop(DropItem.java:60) ~[?:?]
at net.seyarada.pandeloot.drops.DropItem.initDropItem(DropItem.java:54) ~[?:?]
at net.seyarada.pandeloot.drops.DropItem.<init>(DropItem.java:34) ~[?:?]
at net.seyarada.pandeloot.drops.DropManager.dropAction(DropManager.java:102) ~[?:?]
at net.seyarada.pandeloot.drops.DropManager.access$000(DropManager.java:13) ~[?:?]
at net.seyarada.pandeloot.drops.DropManager$1.run(DropManager.java:83) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-623]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-623]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-623]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-623]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-623]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-623]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-623]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

I tried with ytopia and paper.

Example of droptabe:
```
Loot0to10:
  Drops:
    - exp 10-20, 1
    - mmoitems{type=MISCELLANEOUS;id=COIN_COPPER} 1 0.15
    - ...
```
Mob drop:
```
    Drops:
        - potato 1-4 0.05
        - rotten_flesh 1-3 0.5
    Rewards:
        - Loot0to10{top=1;dmg=20%}
        - LootDropTable5to10{top=1;dmg=20%}
```

**Comment by Seyarada** [comment]
You need to indicate the reward is a droptable by using ``droptable`` as the origin, so you would need to change your rewards to:
```yml
Rewards:
- droptable:Loot0to10{top=1;dmg=20%}
- droptable:LootDropTable5to10{top=1;dmg=20%}
```

**Comment by honnisha** [comment]
Thank you!
