### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Tanerx** [Seyarada/PandeLoot#2]
Hello.
I think this error because Purpur. Plugin still working fine.  https://purpur.pl3x.net

`[03:39:49 ERROR]: Could not pass event EntityDeathEvent to MythicMobs v4.11.2
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:148) ~[?:?]
        at net.seyarada.pandeloot.compatibility.mythicmobs.MythicMobsDrop.get(MythicMobsDrop.java:41) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.LootBag.add(LootBag.java:70) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.DropTable.handleDrop(DropTable.java:209) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.DropTable.generate(DropTable.java:191) ~[?:?]
        at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:422) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor277.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1084]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1084]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1084]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1084]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:855) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1622) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1542) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1371) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityInsentient.damageEntity(EntityInsentient.java:349) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:372) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:318) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:595) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2600) ~[patched_1.16.5.jar:git-Purpur-1084]        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:406) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1539) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1143) ~[patched_1.16.5.jar:git-Purpur-1084]        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1563) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1084]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1084]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

`This server is running Purpur version git-Purpur-1084 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

`MMOCore-1.7.1, MMOItems-6.5.7, MythicLib-1.0.19, MythicMobs-4.11.2, PandeLoot-0.1.6i`

**Comment by Seyarada** [comment]
Seems to be caused by the plugin looking for a player to assign a droptable to but not being able to find it, not sure how that could happen ( having the drop part that causes this error would be helpful ) but my guess is that you are trying to drop the droptable with the drop/skill instead of the reward section? I'll add a check to verify the player is there for the next version though

**Comment by Tanerx** [comment]
Spawning Zombie and SkeletonKing configs:

https://i.imgur.com/WRBxINL.png

**Comment by Tanerx** [comment]
Paper server:

`[10:20:24 ERROR]: Could not pass event EntityDeathEvent to MythicMobs v4.11.2
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:148) ~[?:?]
        at net.seyarada.pandeloot.compatibility.mythicmobs.MythicMobsDrop.get(MythicMobsDrop.java:41) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.LootBag.add(LootBag.java:70) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.DropTable.handleDrop(DropTable.java:209) ~[?:?]
        at io.lumine.xikage.mythicmobs.drops.DropTable.generate(DropTable.java:191) ~[?:?]
        at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:422) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor277.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-564]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:829) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1598) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1520) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:366) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:315) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:498) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:959) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:644) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-564]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Seyarada** [comment]
Are you sure the screenshot you posted is what causes that error? The error could only happen if you are trying to drop a MM DropTable, while in the screenshot you aren't dropping anything from MM

**Comment by Tanerx** [comment]
> Are you sure the screenshot you posted is what causes that error? The error could only happen if you are trying to drop a MM DropTable, while in the screenshot you aren't dropping anything from MM

You are right. I forget one in the mobs config.
https://i.imgur.com/m2vhZp3.png
